version: '3.8'

services:
  ui-service:
    build:
      context: .                   # Look at the root folder
      dockerfile: ui-service/Dockerfile # Use the Dockerfile inside ui-service
    container_name: mapreduce-ui
    ports:
      - "8000:8000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=12345678
      - DATABASE_URL=postgresql://mapreduce_user:mapreduce_password@postgres:5432/mapreduce_db
    depends_on:
      - postgres
      - minio

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: mapreduce-keycloak
    command: start-dev # 'start-dev' is perfect for our project; it skips complex SSL setup
    environment:
      # initial admin credentials
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # database configuration
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak_db
      - KC_DB_USERNAME=mapreduce_user #username and password here should match the ones defined in postgres
      - KC_DB_PASSWORD=mapreduce_password
      - KC_HOSTNAME_STRICT=false # allows access via localhost
    ports:
      - "8080:8080"
    depends_on:
      - postgres


  postgres:
    image: postgres:15-alpine
    container_name: mapreduce-postgres
    environment:
      POSTGRES_USER: mapreduce_user
      POSTGRES_PASSWORD: mapreduce_password
      POSTGRES_DB: mapreduce_db # the app's DB
      POSTGRES_MULTIPLE_DATABASES: keycloak_db #keycloak's DB

    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: mapreduce-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    ports:
      - "9000:9000" # api port
      - "9001:9001" # ui port 
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata: