apiVersion: v1
kind: ConfigMap
metadata:
  name: mapreduce-config
data:
  MINIO_ENDPOINT: "mapreduce-minio:9000"
  DATABASE_URL: "postgresql://mapreduce_user:mapreduce_password@mapreduce-postgres:5432/mapreduce_db"
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://mapreduce-postgres:5432/keycloak_db"
  KC_DB_USERNAME: "mapreduce_user"
  KC_HOSTNAME_STRICT: "false"
  MANAGER_SERVICE_URL: "http://manager-service:8000"
  MANAGER_REPLICAS: "3"
  KEYCLOAK_INTERNAL_URL: "http://mapreduce-keycloak:8080"
  # This is the URL that the CLI will use to reach Keycloak. We assume they port-forward to 8080 or hit NodePort.
  KEYCLOAK_EXTERNAL_URL: "http://localhost:8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: mapreduce-secrets
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "admin"
  MINIO_SECRET_KEY: "12345678"
  MINIO_ROOT_USER: "admin"
  MINIO_ROOT_PASSWORD: "12345678"
  POSTGRES_USER: "mapreduce_user"
  POSTGRES_PASSWORD: "mapreduce_password"
  POSTGRES_DB: "mapreduce_db"
  POSTGRES_MULTIPLE_DATABASES: "keycloak_db"
  KC_DB_PASSWORD: "mapreduce_password"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
