from pydantic import BaseModel
from typing import Optional, List
from datetime import datetime
from uuid import UUID

"""
Pydantic Schemas for the MapReduce platform.
These models define the JSON structure for FastAPI request/response bodies.

- Request schemas: what the user SENDS (only user-provided fields)
- Response schemas: what the system RETURNS (all fields from the database)
"""


#schemas for job

class JobCreate(BaseModel):
    """
    Request body for POST /jobs.
    The user provides only the MinIO references to the uploaded files.
    Fields like job_id, status, timestamps are auto-generated by the system.
    """
    input_code_ref: str
    mapper_code_ref: str
    reducer_code_ref: str
    num_mappers: int = 3
    num_reducers: int = 1


class JobResponse(BaseModel):
    """
    Response body for GET /jobs, POST /jobs.
    Returns all job info from the database.
    """
    job_id: UUID
    user_id: str
    status: str
    input_code_ref: str
    mapper_code_ref: str
    reducer_code_ref: str
    output_code_ref: Optional[str] = None
    num_mappers: int = 3
    num_reducers: int = 1
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True  # Allows converting SQLAlchemy objects directly


#schemas for task

class TaskResponse(BaseModel):
    """
    Response body for task details.
    Used when returning task info (e.g., inside a job detail response).
    """
    task_id: UUID
    job_id: UUID
    task_type: str
    status: str
    worker_pod_id: Optional[str] = None
    input_partition_ref: str
    output_partition_ref: Optional[str] = None
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class TaskStatusUpdate(BaseModel):
    """
    Request body for POST /manager/tasks/status.
    Workers send this to report their progress to the Manager.
    """
    task_id: UUID
    status: str
    worker_pod_id: Optional[str] = None
    output_partition_ref: Optional[str] = None


#schemas for job detail

class JobDetailResponse(BaseModel):
    """
    Response body for GET /jobs/{job_id}.
    Returns the job info AND all its tasks, so the user can see
    the full picture of the job's progress.
    """
    job_id: UUID
    user_id: str
    status: str
    input_code_ref: str
    mapper_code_ref: str
    reducer_code_ref: str
    output_code_ref: Optional[str] = None
    num_mappers: int = 3
    num_reducers: int = 1
    created_at: datetime
    updated_at: datetime
    tasks: List[TaskResponse] = []

    class Config:
        from_attributes = True


#schemas for file upload

class FileUploadResponse(BaseModel):
    """
    Response body for POST /files/upload.
    Returns the MinIO references for the uploaded files,
    so the user can use them later in POST /jobs.
    """
    input_ref: Optional[str] = None
    mapper_ref: Optional[str] = None
    reducer_ref: Optional[str] = None

class UserCreate(BaseModel):
    """
    Request body for creating a new user in Keycloak.
    """
    username: str
    password: str
